✨ feat: first dynamic phase
acapolungo/mytetris pull request #5
Opened 2022-05-11 08:57 UTC by acapolungo

A shape made up of a single box. It will appear from the top and move down one line every second. A new one appears in the same way.

issue: #4

2022-05-24 17:17 UTC, dbesserman requested changes

2022-05-25 14:59 UTC, acapolungo commented on src/App.tsx
> +  const [tetrisGrid, updateTetrisGrid] = useState(emptyGrid());
renamed to setTetrisGrid

2022-05-25 15:30 UTC, acapolungo commented on src/App.tsx
> +    if (arrayCopy[count+1]) {
j'ai changé le nom et exporté le tout dans la fonction checkIfRowBelowExist.

2022-05-25 15:30 UTC, acapolungo commented on src/components/Emptycell/Cell.jsx
> +// import { useState } from 'react';
Commentaire supprimé.

2022-05-25 15:30 UTC, acapolungo commented on src/App.tsx
> +// const arrayOfGradients = ['bg-gradient-yellow', 'bg-gradient-orange','bg-gradient-purple','bg-gradient-blue','bg-gradient-red',]
Commentaire supprimé.

2022-05-25 15:33 UTC, acapolungo commented on src/App.tsx
> +    updateTetrisGrid(arrayCopy)
J'ai exporté ce code dans une fonction mais nous avons tout de meme 2 modifications du state, une pour appliquer le style avec 

1/ set interval > style ajouté > puis une mise  à jour du state

2/ setTimeout. style retiré si la ligne du dessous est sans style > puis une mise  à jour du state

2022-05-27 10:21 UTC, dbesserman commented on src/App.tsx
> +        removeShapeColor()
Ici tu as deux fonctions qui font chacune appel à `setTetrisGrid` déclenchant à chaque fois un nouveau rendu du composant. Il faut qu'il n'y ait qu'une seule fonction qui ferait:

vérifier si le prochain mouvement est possible
    - Est-ce qu'il existe une ligne en dessous? && Est-ce que la case du dessous est libre?
    -> Si oui déplacer la forme une case plus bas
    -> Si non arrêter la forme et en faire apparaître une nouvelle par en haut
    
   Comment déplacer la case en une fois?
1. créer une copie de tetrisGrid
2. supprimer la forme active (sans muter le tetrisGrid original)
3. ajouter la forme active une ligne en dessous (sans muter le tetrisGrid original)
4. appeller `setTetrisGrid` une seule fois avec le nouveau grid issue des 2 tranfsormations

2022-05-28 14:06 UTC, dbesserman reviewed
Mes derniers commentaires. Après çà sera bon.

2022-05-28 14:06 UTC, dbesserman commented on src/App.tsx
>    const addShapeColor = useCallback(() => {
il faut renommer cette fonction. Si je lis son nom "ajouter la couleur de la forme forme" je comprends pas vraiment ce que çà fait. De la même manière que tu as appelé une fonction introduceShape, tu peux tout simplement renommer celle-ci `moveShape`

2022-05-28 14:06 UTC, dbesserman commented on src/App.tsx
>      if (checkIfRowBelowExist(tetrisGridCopy, rowIndex) && checkIfRowBelowisTaken(tetrisGridCopy, rowIndex)) {
`checkIfRowBelowisTaken` n'est pas en camelCase

2022-05-28 14:06 UTC, dbesserman commented on src/App.tsx
>    const [rowIndex, setRowIndex] = useState(0);
Plus bas tu te réfères à la ligne actuelle comme le `currentRow`. De manière à être cohérent, il faudrait renommer rowIndex en `currentRowIndex` et setRowIndex en `setCurrentRowIndex`

2022-06-01 12:38 UTC, merged